module.exports = {
  theme: {
    colors: {},
  },
  variants: {},
  plugins: [],
  corePlugins: [
    'preflight',
    'display',
    'cursor',
    'flex',
    'flexDirection',
    'flexGrow',
    'flexShrink',
    'flexWrap',
    'alignItems',
    'alignContent',
    'alignSelf',
    'fontSize',
    'justifyContent',
    'margin',
    'zIndex',
    'textTransform',
    'fontWeight',
    'height',
    'width',
    'padding',
    'borderWidth',
    'position',
    'inset',
    'opacity',
    'maxWidth',
    'boxShadow',
    'borderRadius',
    'overflow',
    'objectFit',
  ]
}
