export const HOME = '/'
export const PORTFOLIO = '/portfolio'
export const ABOUT = '/about'
export const CONTACT = '/contact'
export const RESUME = '/resume'
export const PERSONAL = '/personal'
export const MORE = '/more'
