version: 2
name: Greeting from Mona
on:
  push:
    branches:
      - source

env:
  NODE_ENV: production
  GA_TRACKING_CODE: ${{ secrets.GA_TRACKING_CODE }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        persist-credentials: false

    - name: Build
      run: |
        npm install
        npm run test
        npm run prod
        npm run sitemap
        cp dist/index.html dist/404.html
        cp google21029c74dc702d92.html dist/
        cp robots.txt dist/

    - name: Deploy
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        BRANCH: source
        FOLDER: dist
