name: Build Bundle for Github Pages
on:
  push:
    branches:
      - source

env:
  NODE_ENV: production
  PUBLIC_URL: http://crrmacarse.github.io/
  GA_TRACKING_CODE: ${{ secrets.GA_TRACKING_CODE }}
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        persist-credentials: false

    - name: Build
      run: |
        npm install
        npm run prod:pipeline
        npm run sitemap
        cp dist/index.html dist/404.html
        cp google21029c74dc702d92.html dist/
        cp robots.txt dist/

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: source
        FOLDER: dist
